In [78]:
import numpy as np

In [79]:
# 1. Подключите библиотеку numpy и создайте одномерный массив, в котором по порядку все числа до 100, кратные 5
my_array=np.arange(5,101,5)
my_array

array([  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
        70,  75,  80,  85,  90,  95, 100])

In [80]:
# 2. Из полученного массива получить массив с кратными 10 числами
filtered_array = my_array[my_array % 10 == 0]
filtered_array

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [81]:
# 3. Получить двумерный массив с двумя столбцами
reshaped_array = filtered_array.reshape(5,2)
reshaped_array

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

In [82]:
# 4. Получить набор, в котором все элементы меньше предыдущего на 5
my_second_array = reshaped_array-5
my_second_array

array([[ 5, 15],
       [25, 35],
       [45, 55],
       [65, 75],
       [85, 95]])

In [83]:
# 5. Соедините массивы, полученные в п. 3.1 и 4.1, горизонтально (транспонирование используется для корректного соединения)
combined_array = np.hstack((reshaped_array,my_second_array))
combined_array

array([[ 10,  20,   5,  15],
       [ 30,  40,  25,  35],
       [ 50,  60,  45,  55],
       [ 70,  80,  65,  75],
       [ 90, 100,  85,  95]])

In [84]:
#6.1.Разделите 2 и 3 строку на 4 верхних строки my_array. Используйте .T для транспонирования матрицы
rows_2_and_3 = combined_array[2:4]
print(rows_2_and_3)

first_four_rows = my_array[:rows_2_and_3.size].reshape(rows_2_and_3.shape)
print(first_four_rows)

division_result = rows_2_and_3.T / first_four_rows.T
division_result
print(my_array)


[[50 60 45 55]
 [70 80 65 75]]
[[ 5 10 15 20]
 [25 30 35 40]]
[  5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90
  95 100]


In [85]:
#7.1.	Оставить только те значения, которые не изменились после деления
for i in range(len(rows_2_and_3.T)):   
    if np.array_equal(rows_2_and_3.T[i], division_result[i]):
        print(f"Строка {i} совпадает: {rows_2_and_3.T[i]}")
    else:
        print(f"Строки не совпадают")


Строки не совпадают
Строки не совпадают
Строки не совпадают
Строки не совпадают


In [86]:
#8.1.	Снова получить трехстрочный двумерный массив и поменять местами первую и третью строки
my_array_third = my_array.reshape(5,4)[0:3][::-1]
my_array_third

array([[45, 50, 55, 60],
       [25, 30, 35, 40],
       [ 5, 10, 15, 20]])

In [87]:
#9.1. Получить среднее, медиану и стандартное отклонение для каждой строки, используя команды np.mean(), np.median(), np.std().

print(f"Среднее значение массива: ", np.mean(my_array_third[0]))
print(f"Медиана массива: ", np.median(my_array_third[0]))
print(f"Стандартное отклонение: ", np.std(my_array_third[0]))

print(f"Среднее значение массива: ", np.mean(my_array_third[1]))
print(f"Медиана массива: ", np.median(my_array_third[1]))
print(f"Стандартное отклонение: ", np.std(my_array_third[1]))

print(f"Среднее значение массива: ", np.mean(my_array_third[2]))
print(f"Медиана массива: ", np.median(my_array_third[2]))
print(f"Стандартное отклонение: ", np.std(my_array_third[2]))



Среднее значение массива:  52.5
Медиана массива:  52.5
Стандартное отклонение:  5.5901699437494745
Среднее значение массива:  32.5
Медиана массива:  32.5
Стандартное отклонение:  5.5901699437494745
Среднее значение массива:  12.5
Медиана массива:  12.5
Стандартное отклонение:  5.5901699437494745


In [90]:
#10.1.	Сделать нормализацию на максимальное значение вдоль строк, поделив каждый элемент массива на max() вдоль строк.

my_array_third = my_array_third.astype(np.float32)
for i in range(len(my_array_third)):
     max_value = my_array_third[i].max()
     for j in range(len(my_array_third[i])):
        my_array_third[i][j] = my_array_third[i][j]/max_value
my_array_third 

array([[0.75     , 0.8333333, 0.9166667, 1.       ],
       [0.625    , 0.75     , 0.875    , 1.       ],
       [0.25     , 0.5      , 0.75     , 1.       ]], dtype=float32)

<h1>2.Использование команд библиотеки pandas</h1>

2.1.	Импортируйте данные из файла “Global Population Trends(2016-2022).csv”. Описание данных смотрите ниже.

In [93]:
import pandas as pd
df = pd.read_csv('Global Population Trends(2016-2022).csv')
df

Country  Year Total Population Urban Population Rural Population  \
0     Afghanistan  2017                -                -                -   
1     Afghanistan  2018       36,686,784        9,353,296       27,333,488   
2     Afghanistan  2019       37,769,499        9,727,157       28,042,342   
3     Afghanistan  2020       38,972,230       10,142,913       28,829,317   
4     Afghanistan  2021       40,099,462       10,551,772       29,547,690   
...           ...   ...              ...              ...              ...   
1068     Zimbabwe  2017                -                -                -   
1069     Zimbabwe  2018       15,052,184        4,848,158       10,204,026   
1070     Zimbabwe  2019       15,354,608        4,945,719       10,408,889   
1071     Zimbabwe  2020       15,669,666        5,052,214       10,617,452   
1072     Zimbabwe  2021       15,993,524        5,166,388       10,827,136   

     Population Density Life Expectancy  Birth Rate  Death Rate  \
0                    55              63      37.342       7.027   
1                    56              63      36.927       6.981   
2                    58              64      36.466       6.791   
3                    60              63      36.051       7.113   
4                     -              62      35.842       7.344   
...                 ...             ...         ...         ...   
1068                 38              61      32.516       8.266   
1069                 39              61      32.074       7.972   
1070                 40              61      31.518       8.043   
1071                 41              61      31.009       8.132   
1072                  -              59      30.537       9.057   

     Fertility Rate Infant Mortality Rate Growth Rate  
0             5.129                  49.4           -  
1             5.002                  47.8           3  
2              4.87                  46.3           3  
3              4.75                  44.8           3  
4             4.643                  43.4           3  
...             ...                   ...         ...  
1068          3.706                  39.5           -  
1069          3.659                    38           2  
1070          3.599                  37.1           2  
1071          3.545                  36.6           2  
1072          3.491                  35.7           2  

[1073 rows x 12 columns]

In [95]:
#2.2. Считайте несколько первых записей таблицы (head())
df.head()

Country  Year Total Population Urban Population Rural Population  \
0  Afghanistan  2017                -                -                -   
1  Afghanistan  2018       36,686,784        9,353,296       27,333,488   
2  Afghanistan  2019       37,769,499        9,727,157       28,042,342   
3  Afghanistan  2020       38,972,230       10,142,913       28,829,317   
4  Afghanistan  2021       40,099,462       10,551,772       29,547,690   

  Population Density Life Expectancy  Birth Rate  Death Rate Fertility Rate  \
0                 55              63      37.342       7.027          5.129   
1                 56              63      36.927       6.981          5.002   
2                 58              64      36.466       6.791           4.87   
3                 60              63      36.051       7.113           4.75   
4                  -              62      35.842       7.344          4.643   

  Infant Mortality Rate Growth Rate  
0                  49.4           -  
1                  47.8           3  
2                  46.3           3  
3                  44.8           3  
4                  43.4           3

In [98]:
#2.3. Определите размерность данного фрейма (shape())
df.shape

(1073, 12)

In [100]:
#Выведите название заголовков столбцов фрейма (columns)
df.columns

Index(['Country', 'Year', 'Total Population', 'Urban Population',
       'Rural Population', 'Population Density', 'Life Expectancy',
       'Birth Rate', 'Death Rate', 'Fertility Rate', 'Infant Mortality Rate',
       'Growth Rate'],
      dtype='object')

In [101]:
#2.5.	Получите описание всех переменных (полей) (info())
df.info

<bound method DataFrame.info of           Country  Year Total Population Urban Population Rural Population  \
0     Afghanistan  2017                -                -                -   
1     Afghanistan  2018       36,686,784        9,353,296       27,333,488   
2     Afghanistan  2019       37,769,499        9,727,157       28,042,342   
3     Afghanistan  2020       38,972,230       10,142,913       28,829,317   
4     Afghanistan  2021       40,099,462       10,551,772       29,547,690   
...           ...   ...              ...              ...              ...   
1068     Zimbabwe  2017                -                -                -   
1069     Zimbabwe  2018       15,052,184        4,848,158       10,204,026   
1070     Zimbabwe  2019       15,354,608        4,945,719       10,408,889   
1071     Zimbabwe  2020       15,669,666        5,052,214       10,617,452   
1072     Zimbabwe  2021       15,993,524        5,166,388       10,827,136   

     Population Density Life Ex

In [103]:
#2.6.	 Удалите строки, не содержащие значения в столбце «Total Population» - “-” 
df1=df[df['Total Population']!='-']
df1

Country  Year Total Population Urban Population Rural Population  \
1     Afghanistan  2018       36,686,784        9,353,296       27,333,488   
2     Afghanistan  2019       37,769,499        9,727,157       28,042,342   
3     Afghanistan  2020       38,972,230       10,142,913       28,829,317   
4     Afghanistan  2021       40,099,462       10,551,772       29,547,690   
6         Albania  2018        2,866,376        1,728,969        1,137,407   
...           ...   ...              ...              ...              ...   
1067       Zambia  2021       19,473,125        8,800,295       10,672,830   
1069     Zimbabwe  2018       15,052,184        4,848,158       10,204,026   
1070     Zimbabwe  2019       15,354,608        4,945,719       10,408,889   
1071     Zimbabwe  2020       15,669,666        5,052,214       10,617,452   
1072     Zimbabwe  2021       15,993,524        5,166,388       10,827,136   

     Population Density Life Expectancy  Birth Rate  Death Rate  \
1                    56              63      36.927       6.981   
2                    58              64      36.466       6.791   
3                    60              63      36.051       7.113   
4                     -              62      35.842       7.344   
6                   105              79      10.517       8.308   
...                 ...             ...         ...         ...   
1067                  -              61      34.511       6.973   
1069                 39              61      32.074       7.972   
1070                 40              61      31.518       8.043   
1071                 41              61      31.009       8.132   
1072                  -              59      30.537       9.057   

     Fertility Rate Infant Mortality Rate Growth Rate  
1             5.002                  47.8           3  
2              4.87                  46.3           3  
3              4.75                  44.8           3  
4             4.643                  43.4           3  
6              1.44                   8.3           0  
...             ...                   ...         ...  
1067          4.308                  40.2           3  
1069          3.659                    38           2  
1070          3.599                  37.1           2  
1071          3.545                  36.6           2  
1072          3.491                  35.7           2  

[864 rows x 12 columns]

In [106]:
#2.7.	Получите описательную статистику по переменным (например, max(), min(), describe())
print(df1.describe())
print(df1['Total Population'].max())
print(df1['Total Population'].min())

              Year  Birth Rate  Death Rate
count   864.000000  864.000000  864.000000
mean   2019.500000   18.548384    7.889123
std       1.118682    9.887518    3.041385
min    2018.000000    0.000000    0.000000
25%    2018.750000   10.500000    6.116500
50%    2019.500000   15.628500    7.453500
75%    2020.250000   25.565000    9.385000
max    2021.000000   46.127000   21.700000
99,258
1,057,198


In [114]:
#2.8.	Выполните сортировку данных по нескольким критериям
df1_sorted = df1.sort_values(by=['Urban Population', 'Country'], ascending=[False, True])
df1_sorted


Country  Year Total Population Urban Population  \
696                   Nigeria  2018      198,387,623       99,876,265   
612                    Mexico  2018      124,013,861       99,404,550   
300                   Estonia  2021        1,330,932          923,866   
299                   Estonia  2020        1,329,522          920,415   
400             Guinea-Bissau  2021        2,060,721          919,432   
..                        ...   ...              ...              ...   
505                    Kosovo  2021        1,786,038                -   
904  St. Martin (French Part)  2018           33,852                -   
905  St. Martin (French Part)  2019           33,121                -   
906  St. Martin (French Part)  2020           32,553                -   
907  St. Martin (French Part)  2021           31,948                -   

    Rural Population Population Density Life Expectancy  Birth Rate  \
696       98,511,358                218              53      38.248   
612       24,609,311                 64              74      16.465   
300          407,066                  -              77      10.000   
299          409,107                 31              79       9.900   
400        1,141,289                  -              60      31.087   
..               ...                ...             ...         ...   
505                -                  -              77      11.143   
904                -                677              81      17.022   
905                -                662              80      16.483   
906                -                651              80      15.768   
907                -                  -              80      15.053   

     Death Rate Fertility Rate Infant Mortality Rate Growth Rate  
696      13.239          5.447                  75.5           2  
612       6.856          1.996                  12.6           1  
300      14.000           1.61                   1.6           0  
299      11.900           1.58                   1.7           0  
400       8.716          4.005                    50           2  
..          ...            ...                   ...         ...  
505       7.220          1.522                   9.1           0  
904       4.176          2.517                     -          -2  
905       4.661          2.485                     -          -2  
906       4.788          2.448                     -          -2  
907       4.911          2.415                     -          -2  

[864 rows x 12 columns]

In [110]:
#2.9. Выведите название страны, которая имеет максимальную численность населения
country_max_population = df1.loc[df1['Total Population'].idxmax(), 'Country']
print(country_max_population)

Seychelles


In [115]:
#2.10. Выведите название страны с минимальной численностью населения
country_min_population = df1.loc[df1['Total Population'].idxmin(), 'Country']
print(country_min_population)

Djibouti


In [116]:
# convert to excel
df.to_csv('Global Population Trends(2016-2022).csv')